---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-pythonic
spec:
  package: ghcr.io/fortra/function-pythonic:v0.0.2
#   runtimeConfigRef:
#     name: debug
# ---
# apiVersion: pkg.crossplane.io/v1beta1
# kind: DeploymentRuntimeConfig
# metadata:
#   name: debug
# spec:
#   deploymentTemplate:
#     spec:
#       selector: {}
#       template:
#         spec:
#           containers:
#           - name: package-runtime
#             args:
#             - --debug
