apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: argovclusters.example.crossplane.io
spec:
  group: example.crossplane.io
  names:
    kind: ArgoVCluster
    plural: argovclusters
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: {}
