apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- inline

# Remove the temporary ConfigMap after use
patches:
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: temp
