apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- inline

# Remove the temp ConfigMap after use
# https://www.innoq.com/en/blog/2022/07/advanced-kustomize-features/
patches:
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: temp
