apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: temp
  files:
  - vcluster.py

generatorOptions:
  disableNameSuffixHash: true

resources:
- composition.yaml

replacements:
- source:
    kind: ConfigMap
    name: temp
    fieldPath: data.[vcluster.py]
  targets:
  - select:
      kind: Composition
      name: vclusters.example.joebowbeer.com
    fieldPaths:
    - spec.pipeline.0.input.composite
