---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcluster.cnp.example.org
spec:
  compositeTypeRef:
    apiVersion: cnp.example.org/v1alpha1
    kind: XCluster
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - base:
          apiVersion: helm.crossplane.io/v1beta1
          kind: Release
          metadata:
            annotations:
              crossplane.io/external-name: null
          spec:
            forProvider:
              chart:
                name: vcluster
                repository: https://charts.loft.sh
                version: 0.4.5
              namespace: null
              values:
                syncer:
                  extraArgs: []
                  image: docker.io/willies/vcluster:0.0.1
                vcluster:
                  extraArgs:
                  - --service-cidr=10.43.0.0/16
            rollbackLimit: 3
        name: vcluster-helm-release
        patches:
        - fromFieldPath: metadata.name
          policy:
            fromFieldPath: Required
          toFieldPath: spec.forProvider.namespace
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          policy:
            fromFieldPath: Required
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - string:
              fmt: '%s-vcluster'
              type: Format
            type: string
          type: FromCompositeFieldPath
        - combine:
            strategy: string
            string:
              fmt: --out-kube-config-server=https://%s.%s.svc
            variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.values.syncer.extraArgs[0]
          type: CombineFromComposite
        - combine:
            strategy: string
            string:
              fmt: --tls-san=%s.%s.svc
            variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.values.syncer.extraArgs[1]
          type: CombineFromComposite
      - base:
          apiVersion: cluster.argocd.crossplane.io/v1alpha1
          kind: Cluster
          spec:
            forProvider:
              config:
                tlsClientConfig:
                  caDataSecretRef:
                    key: certificate-authority
                    name: null
                    namespace: null
                  certDataSecretRef:
                    key: client-certificate
                    name: null
                    namespace: null
                  insecure: false
                  keyDataSecretRef:
                    key: client-key
                    name: null
                    namespace: null
              name: null
              server: null
        name: argocd-cluster
        patches:
        - fromFieldPath: metadata.uid
          toFieldPath: metadata.name
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.name
          type: FromCompositeFieldPath
        - combine:
            strategy: string
            string:
              fmt: http://%s.%s.svc
            variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.server
          type: CombineFromComposite
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.config.tlsClientConfig.certDataSecretRef.name
          transforms:
          - string:
              fmt: vc-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.config.tlsClientConfig.certDataSecretRef.namespace
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.config.tlsClientConfig.keyDataSecretRef.name
          transforms:
          - string:
              fmt: vc-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.config.tlsClientConfig.keyDataSecretRef.namespace
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.config.tlsClientConfig.caDataSecretRef.name
          transforms:
          - string:
              fmt: vc-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.config.tlsClientConfig.caDataSecretRef.namespace
          type: FromCompositeFieldPath
      - base:
          apiVersion: kubernetes.crossplane.io/v1alpha1
          kind: Object
          spec:
            forProvider:
              manifest:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  name: null
                  namespace: argocd
                spec:
                  destination:
                    name: null
                    namespace: guestbook
                  project: default
                  source:
                    path: guestbook
                    repoURL: https://github.com/argoproj/argocd-example-apps.git
                    targetRevision: HEAD
                  syncPolicy:
                    automated:
                      prune: true
                    syncOptions:
                    - CreateNamespace=true
        name: argocd-guestbook-application
        patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
          - string:
              fmt: '%s-guestbook'
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.spec.destination.name
          type: FromCompositeFieldPath
    step: patch-and-transform
  writeConnectionSecretsToNamespace: crossplane-system
