apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: vinnie
spec:
  forProvider:
    chart:
      name: vcluster
      repository: https://charts.loft.sh
      version: 0.26.0
    namespace: vinnie
    # wait: true
  providerConfigRef:
    name: helm-provider
