---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcluster.cnp.example.org
spec:
  compositeTypeRef:
    apiVersion: cnp.example.org/v1alpha1
    kind: XCluster
  mode: Pipeline
  pipeline:
  - step: render-templates
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- $xr := getCompositeResource . -}}
          {{- $name := $xr.metadata.name -}}
          {{- $namespace := $name -}}
          ---
          apiVersion: helm.crossplane.io/v1beta1
          kind: Release
          metadata:
            annotations:
              {{ setResourceNameAnnotation $name }}
            name: {{ $name }}
          spec:
            forProvider:
              chart:
                name: vcluster
                repository: https://charts.loft.sh
                version: 0.26.0
              namespace: {{ $namespace }}
              values:
                controlPlane:
                  proxy:
                    extraSANs:
                    - {{ $name }}.{{ $namespace }}
              # wait: true
            providerConfigRef:
              name: helm-provider
            rollbackLimit: 1
  - step: auto-ready
    functionRef:
      name: function-auto-ready
