---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.5.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.10.0
# runtimeConfigRef:
#   name: function-go-templating
# ---
# apiVersion: pkg.crossplane.io/v1beta1
# kind: DeploymentRuntimeConfig
# metadata:
#   name: function-go-templating
# spec:
#   deploymentTemplate:
#     spec:
#       selector: {}
#       template:
#         spec:
#           containers:
#           - name: package-runtime
#             args:
#             - --debug
# ---
# apiVersion: pkg.crossplane.io/v1beta1
# kind: Function
# metadata:
#   name: function-sequencer
# spec:
#   package: xpkg.upbound.io/crossplane-contrib/function-sequencer:v0.2.3
